url: https://glasz.org
blog_title: sheeplog
permalink: /sheeplog/:year/:month/:title.html
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'README.md', 'GitHub-contributions']
comments: false
feed_url: /feed.xml
email: mail@glasz.org
sass:
  style: compressed
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    # formatter: HTML
    # Rouge Options â€º https://github.com/jneen/rouge#full-options
    # css_class: 'highlight'
    # line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
